// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzhIF8xIVrSjS94kDpqz95PAjPMkJFWOs',
    appId: '1:516669608993:web:d7b7c754773b335a287f60',
    messagingSenderId: '516669608993',
    projectId: 'four-b8eb6',
    authDomain: 'four-b8eb6.firebaseapp.com',
    storageBucket: 'four-b8eb6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACDIvxXlWsMaCyTqc5S2526IwG24_7nPA',
    appId: '1:516669608993:android:74537811769d5984287f60',
    messagingSenderId: '516669608993',
    projectId: 'four-b8eb6',
    storageBucket: 'four-b8eb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbM4cane4qAlT25HVt_5VMulWr2Ot3RZA',
    appId: '1:516669608993:ios:78cefb9eca9f2096287f60',
    messagingSenderId: '516669608993',
    projectId: 'four-b8eb6',
    storageBucket: 'four-b8eb6.firebasestorage.app',
    iosBundleId: 'com.example.four',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbM4cane4qAlT25HVt_5VMulWr2Ot3RZA',
    appId: '1:516669608993:ios:78cefb9eca9f2096287f60',
    messagingSenderId: '516669608993',
    projectId: 'four-b8eb6',
    storageBucket: 'four-b8eb6.firebasestorage.app',
    iosBundleId: 'com.example.four',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzhIF8xIVrSjS94kDpqz95PAjPMkJFWOs',
    appId: '1:516669608993:web:1444448b151dd503287f60',
    messagingSenderId: '516669608993',
    projectId: 'four-b8eb6',
    authDomain: 'four-b8eb6.firebaseapp.com',
    storageBucket: 'four-b8eb6.firebasestorage.app',
  );
}
